 image:
   file: .gitpod.Dockerfile

# Commands to start on workspace startup
 tasks:
   - init: sudo apt install bc binutils-dev bison build-essential ca-certificates ccache clang cmake curl file flex git libelf-dev libssl-dev lld make ninja-build python3-dev texinfo u-boot-tools xz-utils zlib1g-dev patchelf -y
     command: bash build.sh
# Ports to expose on workspace startup
 ports:
   - port: 8080
     onOpen: open-preview
